version: '3.5'

services:

 roach1:
    image: cockroachdb/cockroach:v22.1.0
    container_name: roach1
    command: start --insecure --join=roach1,roach2,roach3  --accept-sql-without-tls 
    volumes:
      - "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"
    networks:
      cockroachdb_net:
        aliases:
          - roach1

 roach2:
    image: cockroachdb/cockroach:v22.1.0
    container_name: roach2
    command: start --insecure --join=roach1,roach2,roach3   --accept-sql-without-tls 
    volumes:
      - "${PWD}/cockroach-data/roach2:/cockroach/cockroach-data"
    networks:
      cockroachdb_net:
        aliases:
          - roach2

 roach3:
    image: cockroachdb/cockroach:v22.1.0
    container_name: roach3
    command: start --insecure --join=roach1,roach2,roach3  --accept-sql-without-tls 
    volumes:
      - "${PWD}/cockroach-data/roach3:/cockroach/cockroach-data"
    networks:
      cockroachdb_net:
        aliases:
          - roach3

 haproxy:
   build: haproxy
   depends_on:
     - roach1
     - roach2
     - roach3
   ports:
     - "26257:26257"
     - "8080:8080"
     - "8081:8081" 
   networks:
     cockroachdb_net:
       aliases:
         - haproxy

 init:
    image: cockroachdb/cockroach:v22.1.0
    command: init --insecure --host=roach1
    depends_on:
      - roach1
    networks:
      cockroachdb_net:
        aliases:
          - init



networks:
    cockroachdb_net:
        driver: bridge
