version: '3.5'

services:

 roach1:
    image: cockroachdb/cockroach:v21.2.4
    container_name: roach1
    command: start --insecure --join=roach1,roach2,roach3  --accept-sql-without-tls 
    volumes:
      - "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"
    networks:
      cockroachdb_net:
        aliases:
          - roach1

 roach2:
    image: cockroachdb/cockroach:v21.2.4
    container_name: roach2
    command: start --insecure --join=roach1,roach2,roach3   --accept-sql-without-tls 
    volumes:
      - "${PWD}/cockroach-data/roach2:/cockroach/cockroach-data"
    networks:
      cockroachdb_net:
        aliases:
          - roach2

 roach3:
    image: cockroachdb/cockroach:v21.2.4
    container_name: roach3
    command: start --insecure --join=roach1,roach2,roach3  --accept-sql-without-tls 
    volumes:
      - "${PWD}/cockroach-data/roach3:/cockroach/cockroach-data"
    networks:
      cockroachdb_net:
        aliases:
          - roach3

 init:
    container_name: init
    image: cockroachdb/cockroach:v21.2.4
    command: init --host=roach1 --insecure
    depends_on:
      - roach1

 haproxy:
    build: haproxy
    depends_on:
      - roach1
      - roach2
      - roach3
    ports:
      - "26257:26257"
      - "8080:8080"
      - "8081:8081"
    networks:
      cockroachdb_net:
        aliases:
          - haproxy

      
networks:
    cockroachdb_net:
        driver: bridge
